config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :users
root 'static_pages#home'
get  '/signup',  to: 'users#new'
get 'scoresheets' => 'scoresheets#index'
get 'scoresheets/:id' => 'scoresheets#edit'
post 'scoresheets/:id' => 'scoresheets#edit'
patch 'scoresheets/:id' => 'scoresheets#update'
#get '/scoresheets/edit', to: 'scoresheets#edit'
post '/signup',  to: 'users#create'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
resources :scoresheets,  only: [:index, :create, :destroy, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scoresheet.rb
class Scoresheet < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :teamnumber, presence: true
end

app/models/user.rb
class User < ApplicationRecord
 
  has_many :scoresheets, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
def feed
    Scoresheet.where("user_id = ?", id)
end
  
class << self
  # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end
end


  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/scoresheets_controller.rb
class ScoresheetsController < ApplicationController
    before_action :logged_in_user, only: [:index, :create, :destroy,:edit, :show]
    before_action :correct_user,   only: [:index, :edit, :show]
   
  
  def index
    @scoresheet =Scoresheet.new
  end
  def create
    @users = User.all
    @users.each do |user|
      @scoresheet = user.scoresheets.build(team_params)
      if @scoresheet.save
        flash[:success] = "team created!"
        
      else
        
      end
    end
    redirect_to root_url
  end


  def show
     render 'static_pages/test'
  end

  def destroy
  end
  def edit
    
    if current_user.admin?
        @scoresheet =Scoresheet.find_by(id: params[:id])
      else
    @scoresheet = current_user.scoresheets.find(params[:id])
  end
  end
  
  
  def update
    @scoresheet =current_user.scoresheets.find(params[:id])
    if @scoresheet.update_attributes(scoresheet_params)
      flash[:success] = "Profile updated"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  
  private

    def team_params
     
      params.require(:scoresheet).permit(:teamnumber)
    
    end
    def scoresheet_params
     
      params.require(:scoresheet).permit(:teamnumber,:correctness,:creativity,:relevence,:sustainability,:userexperience)
    
    end
    def correct_user
      if current_user.admin?
        @scoresheet =Scoresheet.find_by(id: params[:id])
      else
      
      @scoresheet = current_user.scoresheets.find_by(id: params[:id])
      
      redirect_to root_url if @scoresheet.nil?
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      
      redirect_to user
    else
       flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
    if logged_in?
      @scoresheet  = current_user.scoresheets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:index,:show,:edit, :update]
  before_action :admin_user,     only: :index
  def show
    @user = User.find(params[:id])
    @scoresheets = @user.scoresheets.paginate(page: params[:page])
  end
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def correct_user
     
      if ( current_user.admin?)
        
    else
       @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
      #
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "matin app"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/scoresheets_helper.rb
module ScoresheetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  def current_user?(user)
    user == current_user
    
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The web application course by matin hosseini
  </small>
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if logged_in? %>
        <% if current_user.admin?  %>
    |<li><%= link_to "Users", users_path %></li>
    <li><%= link_to "Teams", scoresheets_path %></li>
  <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/scoresheets/_scoresheet.html.erb
<li id="scoresheet-<%= scoresheet.id %>">
  <%= link_to gravatar_for(scoresheet.user, size: 50), scoresheet.user %>
  <span class="user"><%= link_to scoresheet.user.name, scoresheet.user %></span>
  <span class="teamnumber"><%= scoresheet.teamnumber %></span>
  <% if current_user.admin?  %>
  <%= link_to "show", scoresheet, method: :show %>
  <%else%>
  <%= link_to "edit", scoresheet, method: :edit %>
  <% end %>
</li>

app/views/scoresheets/edit.html.erb
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="scoresheet_form">
        <%= render 'shared/scoresheet_form' %>
      </section>
    </aside>
  </div>

app/views/scoresheets/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@scoresheet) do |f| %>
      <%= f.label :teamnumber %>
      <%= f.text_field :teamnumber %>
      <%= f.submit "Create New Team", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_scoresheet_form.html.erb
<%= form_for(@scoresheet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
       <%= f.label :teamnumber %>
      <%= f.text_field :teamnumber, class: 'form-control', :readonly => true %>
   <%= f.label :correctness %>
  
 
<%= f.select :correctness, [ 1, 2, 3, 4, 5 ], :prompt => 'Select One'  %>

    <%= f.label :creativity %>
      <%= f.select :creativity, [ 1, 2, 3, 4, 5 ], :prompt => 'Select One' %>
    <%= f.label :relevence %>
      <%= f.select :relevence, [ 1, 2, 3, 4, 5 ], :prompt => 'Select One' %>
    <%= f.label :sustainability %>
      <%= f.select :sustainability, [ 1, 2, 3, 4, 5 ], :prompt => 'Select One' %>
    <%= f.label :"user experience" %>
      <%= f.select :userexperience, [ 1, 2, 3, 4, 5 ], :prompt => 'Select One' %>

 
  </div>
  <% if current_user.admin?  %>
  <%else %>
  <%= f.submit "Post", class: "btn btn-primary" %>
  
<% end %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.scoresheets.count, "scoresheet") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
     <h1>Welcome to the judge App</h1>

  <h2>
    This is the home page for the
    judge application.
  </h2>
  </div>
<% else %>

<div class="center jumbotron">
  <h1>Welcome to the judge App</h1>

  <h2>
    This is the home page for the
    judge application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/static_pages/test.html.erb
hello

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
   <div class="col-md-8">
    <% if @user.scoresheets.any? %>
      <h3>Scoresheets (<%= @user.scoresheets.count %>)</h3>
      <ol class="scoresheets">
        <%= render @scoresheets %>
      </ol>
      <%= will_paginate @scoresheets %>
    <% end %>
  </div>
</div>